name: pre-commit

on:
    pull_request:
    push:
        branches: [dev]

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: 3.7.x
            - uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: '6.0.x'
                  include-prerelease: true
            - uses: pre-commit/action@v2.0.0
